apiVersion: v1
kind: ReplicationController
metadata:
  name: cassandra
  labels:
    name: cassandra
spec:
  replicas: 1
  selector:
    name: cassandra
  template:
    metadata:
      labels:
        name: cassandra
    spec:
      containers:
      - name: cassandra
        image: duelle/edcc:cassandra
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    name: cassandra
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector: 
    name: cassandra
